name: 'IssueYAML'
description: 'Create GitHub issues from a YAML Config'
inputs:
  github-token:  # id of input
    description: 'Token to create issues outside the Action repo'
    default: ${{ github.token }}
  path-to-yaml-issues:  # id of input
    description: 'Directory containing IssueYAML'
    default: '${{ github.workspace }}/issues/'
runs:
  using: 'node12'
  main: 'index.js'
